# Generated by Django 6.0.4 on 2026-05-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review_store_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
